# Copyright (c) 2023 Bjarki Arge Andreasen
# SPDX-License-Identifier: Apache-2.0
CONFIG_POSIX_API=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONTEXT_RCVTIMEO=y

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_NET_L2_PPP_OPTION_DNS_USE=y

# Network management
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_CONNECTION_MANAGER=y

# Modem driver
CONFIG_MODEM=y
CONFIG_PM_DEVICE=y
CONFIG_MODEM_CELLULAR=y
CONFIG_MODEM_IFACE_UART_INTERRUPT=n
CONFIG_MODEM_IFACE_UART_ASYNC=y

# Dynamic APN configuration (uncomment if not needed)
#CONFIG_MODEM_CELLULAR_APN="" # Remove default APN
#CONFIG_SAMPLE_CELLULAR_MODEM_AUTO_APN=y
#CONFIG_SAMPLE_CELLULAR_APN_0="shared.m2m.ch"
#CONFIG_SAMPLE_CELLULAR_IMSI_LIST_0="22801"
#CONFIG_SAMPLE_CELLULAR_APN_1="em"
#CONFIG_SAMPLE_CELLULAR_IMSI_LIST_1="29505 90143 29509"
CONFIG_MODEM_QUECTEL_BG9X_APN="soracom.io"
CONFIG_MODEM_QUECTEL_BG9X_USERNAME="sora"
CONFIG_MODEM_QUECTEL_BG9X_PASSWORD="sora"

# Statistics
#CONFIG_MODEM_STATS=y
#CONFIG_SHELL=y

# Testing
#CONFIG_MODEM_AT_SHELL=y
#CONFIG_PM_DEVICE_SHELL=y
#CONFIG_SHELL_WILDCARD=n

CONFIG_GPIO=y

# Logging
CONFIG_LOG=y
CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y
# For extra verbosity
#CONFIG_MODEM_CMUX_LOG_LEVEL_DBG=y
#CONFIG_LOG_BUFFER_SIZE=65536

# Added automatically by Workbench for Zephyr
#--- DEBUG PRESET - BEGIN ---#
# Set to -Og
CONFIG_DEBUG_OPTIMIZATIONS=y
# Thread awareness support
CONFIG_DEBUG_THREAD_INFO=y
# Generate stack usage per-function
CONFIG_STACK_USAGE=y
# Other options in case not set by default
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_BUILD_OUTPUT_META=y
CONFIG_OUTPUT_SYMBOLS=y
CONFIG_OUTPUT_STAT=y
CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
#--- DEBUG PRESET - END ---#
